# -*- coding: utf-8 -*-
"""Copy of tabula_example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zO8TDKAHVV1pTfJT7NEUlop9Ilkph703

# Final Exam Data
tabula-py

## Check Java environment and install tabula-py

tabula-py requires java environment so let's check the java environment on your machine.
"""

!java -version

"""After confirming the java environment, install tabula-py by using pip."""

# To be more precisely, it's better to use `{sys.executable} -m pip install tabula-py`
!pip install -q tabula-py

"""Before trying tabula-py, check your environment via tabula-py `environment_info()` function, which shows Python version, Java version, and your OS environment."""

import tabula

tabula.environment_info()

pdf_path = "https://mcgill.ca/exams/files/exams/april_2020_tentative_exam_schedule_1.pdf"
tabula.convert_into(pdf_path, "test.csv", output_format="csv", pages="all", stream=True)

import pandas as pd
df = pd.read_csv("./test.csv")
df.to_json("data.json", orient='index')

import json
def keep(item:dict):
    if ('COURSE NUMBER' != item.get('COURSE NUMBER')):
        return True
    else:
        return False
with open("data.json", "r") as read_file:
    data = json.load(read_file)
    data = list(data.values())
    data = list(filter(keep, data))
    print(data)
    open("washed.json", "w").write(json.dumps(data))